[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = ""
  NODE_ENV = "development"
  REACT_APP_API_URL = "https://qyqqhtwrtbjdcupvawbs.supabase.co/rest/v1"
  REACT_APP_FRONTEND_URL = "https://omnifyblogss.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 