services:
  # Backend Django API
  - type: web
    name: blog-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements_production.txt
    startCommand: gunicorn blog_backend.wsgi:application
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://blog-frontend.onrender.com
    autoDeploy: true

  # Frontend React App
  - type: web
    name: blog-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://blog-backend.onrender.com/api
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: blog-database
    databaseName: blog_db
    user: blog_user
    plan: free 